#!/usr/bin/env python3
"""Classifier variance appendix — N runs, no '8/8' seal while C1 is red.

Writes docs/VARIANCE-APPENDIX.md and prints a JSON summary.
"""
from __future__ import annotations

import json
import os
import sys
import time
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

N = int(os.environ.get("VARIANCE_N", "10"))
OUT = ROOT / "docs" / "VARIANCE-APPENDIX.md"


def main():
    from contract.task_class import CONTROLS
    from contract.gemini_impl import classify_gemini

    rows = []
    for i in range(N):
        run = {"run": i + 1, "cells": {}}
        for cid, a, b, expected, _why in CONTROLS:
            got = classify_gemini(a, b)
            run["cells"][cid] = {"expected": expected, "got": got,
                                 "ok": got == expected}
            time.sleep(float(os.environ.get("GEMINI_PACE_SECONDS", "0.4")))
        run["pass"] = sum(1 for c in run["cells"].values() if c["ok"])
        rows.append(run)
        print(f"run {i+1}/{N}: {run['pass']}/{len(CONTROLS)}", flush=True)

    # per-control stability
    by_c = {}
    for cid, *_ in CONTROLS:
        gots = [r["cells"][cid]["got"] for r in rows]
        oks = [r["cells"][cid]["ok"] for r in rows]
        by_c[cid] = {
            "ok_rate": sum(oks) / N,
            "modes": dict(Counter(gots)),
            "stable": len(set(gots)) == 1,
        }

    passes = [r["pass"] for r in rows]
    summary = {
        "n": N,
        "pass_range": [min(passes), max(passes)],
        "pass_mean": sum(passes) / N,
        "controls": by_c,
        "c1_ok_rate": by_c.get("C1", {}).get("ok_rate"),
        "seal_forbidden": by_c.get("C1", {}).get("ok_rate", 0) < 1.0,
    }

    lines = [
        "# VARIANCE APPENDIX — classifier stability",
        "",
        f"**N={N}** live Gemini runs against the eight-row control set. "
        "No '8/8' seal while C1 is red.",
        "",
        f"- Pass range: **{min(passes)}–{max(passes)} / 8**",
        f"- Mean: **{sum(passes)/N:.2f} / 8**",
        f"- C1 ok-rate: **{summary['c1_ok_rate']:.0%}** "
        f"({'SEAL FORBIDDEN' if summary['seal_forbidden'] else 'clean'})",
        "",
        "| Control | ok-rate | stable | modes |",
        "|---|---|---|---|",
    ]
    for cid, *_ in CONTROLS:
        c = by_c[cid]
        lines.append(
            f"| {cid} | {c['ok_rate']:.0%} | {'yes' if c['stable'] else 'no'} | "
            f"`{c['modes']}` |"
        )
    lines += [
        "",
        "## Claim allowed in pitch / sealed prediction",
        "",
        "> Gemini beats the substring stub on C5/C6 traps across N runs; "
        "C1 remains a known red row and is not sealed as solved.",
        "",
        f"_Generated by `python3 scripts/variance_appendix.py` · N={N}_",
        "",
    ]
    OUT.write_text("\n".join(lines))
    print(json.dumps(summary, indent=2))
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
